import type { AgentCapabilityDefinition } from '../types';

export const SOCIAL_CAPABILITIES: AgentCapabilityDefinition[] = [
  {
    id: 'social.tiktok.collect',
    skillName: 'social-data-collector',
    title: 'TikTok 数据采集',
    description: '采集 TikTok 爆款视频、账号与可选评论，用于爆款复刻、博主蒸馏和用户语言分析。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/social-scraper/start',
    method: 'POST',
    async: true,
    maxWaitSeconds: 900,
    estimatedDurationSeconds: 180,
    featureKey: 'social_tiktok_collect',
    tags: ['tiktok', 'social', 'collection', 'creator-research'],
    inputSchema: {
      mode: { type: 'string', default: 'keyword', description: '采集模式：keyword / creator / video。', enum: ['keyword', 'creator', 'video'] },
      queries: { type: 'string[]', description: 'keyword 模式下的搜索关键词。' },
      keywords: { type: 'string[]', description: 'keyword 模式下的搜索关键词别名。' },
      targets: { type: 'string[]', description: 'creator 模式下的账号名或账号 URL，例如 @creator。' },
      creators: { type: 'string[]', description: 'creator 模式下的账号名列表。' },
      urls: { type: 'string[]', description: 'video 模式下的视频 URL，或 creator 模式下的账号 URL。' },
      limit: { type: 'number', default: 30, description: '目标采集数量。' },
      sortBy: { type: 'string', default: 'likes', description: '排序方式：likes / views / comments / shares / recent。' },
      collectComments: { type: 'boolean', default: false, description: '是否采集评论。' },
    },
    outputSchema: {
      items: { type: 'array', description: '归一化内容列表。' },
      creators: { type: 'array', description: '创作者列表。' },
      comments: { type: 'array', description: '评论列表。' },
    },
  },
  {
    id: 'social.instagram.collect',
    skillName: 'social-data-collector',
    title: 'Instagram 数据采集',
    description: '采集 Instagram 账号、帖子或 Reels 数据。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/social-scraper/start',
    method: 'POST',
    async: true,
    maxWaitSeconds: 900,
    estimatedDurationSeconds: 180,
    featureKey: 'social_instagram_collect',
    tags: ['instagram', 'social', 'collection'],
    inputSchema: {
      queries: { type: 'string[]', description: '关键词或账号。' },
      urls: { type: 'string[]', description: '帖子或账号 URL。' },
      limit: { type: 'number', default: 30, description: '目标采集数量。' },
    },
    outputSchema: {
      items: { type: 'array', description: '归一化内容列表。' },
      creators: { type: 'array', description: '创作者列表。' },
    },
  },
  {
    id: 'social.facebook.collect',
    skillName: 'social-data-collector',
    title: 'Facebook 数据采集',
    description: '采集 Facebook 公开页面、帖子或相关爆款内容。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/social-scraper/start',
    method: 'POST',
    async: true,
    maxWaitSeconds: 900,
    estimatedDurationSeconds: 180,
    featureKey: 'social_facebook_collect',
    tags: ['facebook', 'social', 'collection'],
    inputSchema: {
      queries: { type: 'string[]', description: '关键词或页面。' },
      urls: { type: 'string[]', description: '帖子或页面 URL。' },
      limit: { type: 'number', default: 30, description: '目标采集数量。' },
    },
    outputSchema: {
      items: { type: 'array', description: '归一化内容列表。' },
      creators: { type: 'array', description: '主页/创作者列表。' },
    },
  },
  {
    id: 'social.comments.collect',
    skillName: 'social-data-collector',
    title: '社媒评论抓取',
    description: '抓取 TikTok 等平台评论，用于用户语言、痛点、异议和购买意图分析。',
    status: 'available',
    executionType: 'n8n_workflow',
    async: true,
    maxWaitSeconds: 900,
    estimatedDurationSeconds: 180,
    featureKey: 'social_comments_collect',
    tags: ['comments', 'audience-language', 'tiktok'],
    inputSchema: {
      platform: { type: 'string', required: true, description: '平台，如 tiktok。' },
      urls: { type: 'string[]', required: true, description: '帖子/视频 URL 列表。' },
      limit: { type: 'number', default: 100, description: '评论数量上限。' },
    },
    outputSchema: {
      comments: { type: 'array', description: '评论列表。' },
      clusters: { type: 'array', description: '可选的评论聚类结果。' },
    },
  },
];
