import type { AgentCapabilityDefinition } from '../types';

export const VIDEO_CAPABILITIES: AgentCapabilityDefinition[] = [
  {
    id: 'digital-human.video.generate',
    skillName: 'digital-human-generator',
    title: '视频数字人生成',
    description: '使用人物图、文案和声音生成口播数字人视频。最长可能 60 分钟。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/digital-human/videos',
    method: 'POST',
    async: true,
    maxWaitSeconds: 3600,
    estimatedDurationSeconds: 1200,
    featureKey: 'digital_human',
    creditModelKey: 'flow_digital_human',
    workflowId: 'flow_Digital_Human',
    workflowName: '数字人 / Digital Human',
    tags: ['digital-human', 'video', 'long-running'],
    inputSchema: {
      personImage: { type: 'string', required: true, description: '人物图片 URL。' },
      script: { type: 'string', required: true, description: '口播文案。' },
      voiceId: { type: 'string', description: '声音 ID 或预设。' },
      duration: { type: 'number', description: '目标时长，秒。' },
    },
    outputSchema: {
      videoUrl: { type: 'string', description: '生成视频 URL。' },
      taskId: { type: 'string', description: '内部任务 ID。' },
    },
  },
  {
    id: 'motion.replication.image_to_video',
    skillName: 'motion-replication',
    title: '动作复刻',
    description: '使用一张人物图片，让图片人物按参考视频动作生成视频。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/action-transfer/videos',
    method: 'POST',
    async: true,
    maxWaitSeconds: 3600,
    estimatedDurationSeconds: 900,
    featureKey: 'action_transfer',
    creditModelKey: 'flow_action_transfer_wan_animate',
    workflowId: 'flow_action_transfer_wan_animate',
    workflowName: '动作复刻',
    tags: ['motion', 'replication', 'image-to-video'],
    inputSchema: {
      personImage: { type: 'string', required: true, description: '待驱动人物图片。' },
      motionReferenceVideo: { type: 'string', required: true, description: '动作参考视频。' },
      duration: { type: 'number', default: 5, description: '目标时长，秒。' },
    },
    outputSchema: {
      videoUrl: { type: 'string', description: '动作复刻视频 URL。' },
    },
  },
  {
    id: 'viral.midform.video.generate',
    skillName: 'viral-midform-video-generator',
    title: '爆款中视频生成',
    description: '生成 3D 骨骼等主题化中视频，未来支持更多主题。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/my-works/t2v',
    method: 'POST',
    async: true,
    maxWaitSeconds: 3600,
    estimatedDurationSeconds: 1200,
    featureKey: 'storyboard_video',
    creditModelKey: 'veo3.1-fast',
    tags: ['midform-video', 'storyboard', '3d-skeleton'],
    inputSchema: {
      theme: { type: 'string', required: true, default: '3d-skeleton', description: '中视频主题。' },
      topic: { type: 'string', required: true, description: '视频主题或选题。' },
      duration: { type: 'number', default: 60, description: '目标时长，秒。' },
    },
    outputSchema: {
      script: { type: 'string', description: '生成脚本。' },
      finalVideoUrl: { type: 'string', description: '最终视频 URL。' },
      segments: { type: 'array', description: '分段视频结果。' },
    },
  },
  {
    id: 'viral.breakdown.video_prompts',
    skillName: 'viral-breakdown-to-video-prompts',
    title: '爆款拆解并反推视频提示词',
    description: '拆解爆款视频/图文结构，并反推可用于视频模型的提示词与 reference contract。MVP 接入图文复刻任务创建与视频文案提取链路。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/image-text-replication/start',
    method: 'POST',
    async: true,
    maxWaitSeconds: 900,
    estimatedDurationSeconds: 180,
    featureKey: 'image_text_replication',
    workflowName: '图文/视频复刻拆解',
    tags: ['viral-breakdown', 'video-prompts', 'replication'],
    inputSchema: {
      referenceUrl: { type: 'string', description: '参考爆款链接。' },
      referenceVideo: { type: 'string', description: '参考视频 URL。' },
      targetProduct: { type: 'object', description: '目标产品信息。' },
      promptProvider: { type: 'string', default: 'seedance', description: '目标视频模型或提示词格式。' },
    },
    outputSchema: {
      breakdown: { type: 'object', description: '爆款拆解结果。' },
      referenceContract: { type: 'object', description: '学习/禁止复制契约。' },
      videoPrompts: { type: 'array', description: '分段视频提示词。' },
    },
  },
];
