import type { AgentCapabilityDefinition } from '../types';

export const VIDEO_CAPABILITIES: AgentCapabilityDefinition[] = [
  {
    id: 'digital-human.video.generate',
    skillName: 'digital-human-generator',
    title: '视频数字人生成',
    description: '使用人物图、文案和声音生成口播数字人视频。最长可能 60 分钟。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/digital-human/videos',
    method: 'POST',
    async: true,
    maxWaitSeconds: 3600,
    estimatedDurationSeconds: 1200,
    featureKey: 'digital_human',
    creditModelKey: 'flow_digital_human',
    workflowId: 'flow_Digital_Human',
    workflowName: '数字人 / Digital Human',
    tags: ['digital-human', 'video', 'long-running'],
    inputSchema: {
      personImage: { type: 'string', required: true, description: '人物图片 URL。' },
      script: { type: 'string', required: true, description: '口播文案。' },
      voiceId: { type: 'string', description: '声音 ID 或预设。' },
      duration: { type: 'number', description: '目标时长，秒。' },
    },
    outputSchema: {
      videoUrl: { type: 'string', description: '生成视频 URL。' },
      taskId: { type: 'string', description: '内部任务 ID。' },
    },
  },
  {
    id: 'motion.replication.image_to_video',
    skillName: 'motion-replication',
    title: '动作复刻',
    description: '使用一张人物图片，让图片人物按参考视频动作生成视频。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/action-transfer/videos',
    method: 'POST',
    async: true,
    maxWaitSeconds: 3600,
    estimatedDurationSeconds: 900,
    featureKey: 'action_transfer',
    creditModelKey: 'flow_action_transfer_wan_animate',
    workflowId: 'flow_action_transfer_wan_animate',
    workflowName: '动作复刻',
    tags: ['motion', 'replication', 'image-to-video'],
    inputSchema: {
      personImage: { type: 'string', required: true, description: '待驱动人物图片。' },
      motionReferenceVideo: { type: 'string', required: true, description: '动作参考视频。' },
      duration: { type: 'number', default: 5, description: '目标时长，秒。' },
    },
    outputSchema: {
      videoUrl: { type: 'string', description: '动作复刻视频 URL。' },
    },
  },
  {
    id: 'viral.midform.video.generate',
    skillName: 'viral-midform-video-generator',
    title: '爆款中视频生成',
    description: '生成 3D 骨骼等主题化中视频，未来支持更多主题。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/my-works/t2v',
    method: 'POST',
    async: true,
    maxWaitSeconds: 3600,
    estimatedDurationSeconds: 1200,
    featureKey: 'storyboard_video',
    creditModelKey: 'veo3.1-fast',
    tags: ['midform-video', 'storyboard', '3d-skeleton'],
    inputSchema: {
      theme: { type: 'string', required: true, default: '3d-skeleton', description: '中视频主题。' },
      topic: { type: 'string', required: true, description: '视频主题或选题。' },
      duration: { type: 'number', default: 60, description: '目标时长，秒。' },
    },
    outputSchema: {
      script: { type: 'string', description: '生成脚本。' },
      finalVideoUrl: { type: 'string', description: '最终视频 URL。' },
      segments: { type: 'array', description: '分段视频结果。' },
    },
  },
  {
    id: 'viral.breakdown.video_prompts',
    skillName: 'viral-breakdown-to-video-prompts',
    title: '爆款拆解并反推视频提示词',
    description: '调用小程序「爆款复刻 / 智能复刻」viral_clone 分镜拆解链路，拆解参考视频并生成可用于 Seedance/Veo 的分段 imagePrompt/videoPrompt。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/miniapp/storyboard/viral-clone/jobs',
    method: 'POST',
    async: true,
    maxWaitSeconds: 900,
    estimatedDurationSeconds: 180,
    featureKey: 'storyboard_breakdown',
    workflowId: 'flow_storyboard_disassembly',
    workflowName: '分镜拆解',
    tags: ['viral-breakdown', 'video-prompts', 'replication', 'viral-clone', 'smart-remix'],
    inputSchema: {
      referenceUrl: { type: 'string', description: '参考爆款视频链接；没有 referenceVideo 时会作为 reference_video_url 使用。' },
      referenceVideo: { type: 'string', description: '参考视频 URL，优先使用。' },
      productId: { type: 'string', description: '可选，用户产品库中的产品 ID，用于智能复刻替换产品。' },
      targetProduct: { type: 'object', description: '目标产品信息；如包含 id/productId 会映射为 product_id。' },
      durationSeconds: { type: 'number', required: true, description: '目标复刻视频时长，秒。必须由用户确认，常用值：15 / 30 / 60。' },
      targetLanguage: { type: 'string', required: true, enum: ['source', 'zh-CN', 'en', 'ja', 'ko', 'es'], description: '目标语言。必须由用户用中文选项确认：跟随原视频 / 中文 / 英文 / 日语 / 韩语 / 西语；内部值分别映射为 source / zh-CN / en / ja / ko / es。' },
      promptProvider: { type: 'string', default: 'seedance', description: '目标视频模型或提示词格式。' },
    },
    outputSchema: {
      taskId: { type: 'string', description: 'StoryboardTask ID。' },
      status: { type: 'string', description: '任务状态，例如 ANALYZING / BREAKDOWN_COMPLETED。' },
      breakdown: { type: 'object', description: '回调完成后写入 StoryboardTask.detailedBreakdown 的爆款拆解结果。' },
      videoPrompts: { type: 'array', description: '回调完成后写入 StoryboardSegment.videoPrompt 的分段视频提示词。' },
    },
  },
];
