import type { AgentCapabilityDefinition } from '../types';

export const WRITING_CAPABILITIES: AgentCapabilityDefinition[] = [
  {
    id: 'content.hook.design',
    skillName: 'short-video-hook-designer',
    title: '短视频 Hook 设计',
    description: '把模糊短视频开头、产品卖点或脚本想法转成明确 Hook Brief：观众问题、开头机制、产品露出时机、风险和下游交付。',
    status: 'available',
    executionType: 'local_agent',
    async: false,
    maxWaitSeconds: 0,
    estimatedDurationSeconds: 60,
    featureKey: 'smart_creation',
    tags: ['hook', 'short-video', 'local-agent', 'pre-generation'],
    inputSchema: {
      brief: { type: 'string', required: true, description: '短视频开头想法、产品卖点或脚本需求。' },
      audience: { type: 'string', description: '目标观众。' },
      productRevealPreference: { type: 'string', description: '产品露出偏好：early / delayed / hidden-until-proof。' },
    },
    outputSchema: {
      hookBrief: { type: 'object', description: 'Hook goal、viewer question、mechanism、product reveal rule 等。' },
    },
  },
  {
    id: 'reference.decode',
    skillName: 'reference-opening-decoder',
    title: '参考开头结构解码',
    description: '把爆款参考视频、首帧或分镜拆成可复用开头结构：hook essence、viewer question、must-copy visual grammar、forbidden drift。',
    status: 'available',
    executionType: 'local_agent',
    async: false,
    maxWaitSeconds: 0,
    estimatedDurationSeconds: 90,
    featureKey: 'smart_creation',
    tags: ['reference', 'hook', 'decode', 'short-video', 'local-agent'],
    inputSchema: {
      referenceSummary: { type: 'string', required: true, description: '参考视频/首帧/分镜/benchmark 的描述或已拆解结果。' },
      targetProduct: { type: 'string', description: '要迁移到的新产品或内容主题。' },
    },
    outputSchema: {
      decodedOpening: { type: 'object', description: 'Hook essence、viewer question、must-copy grammar、forbidden drift。' },
    },
  },
  {
    id: 'prompt.preflight.qa',
    skillName: 'video-prompt-preflight-qa',
    title: '视频提示词生成前 QA',
    description: '在消耗积分前检查短视频 prompt、分镜或 AI 视频生成请求，识别弱开头、产品过早露出、漂移风险和缺少约束。',
    status: 'available',
    executionType: 'local_agent',
    async: false,
    maxWaitSeconds: 0,
    estimatedDurationSeconds: 60,
    featureKey: 'smart_creation',
    tags: ['prompt-qa', 'preflight', 'video', 'cost-guard', 'local-agent'],
    inputSchema: {
      prompt: { type: 'string', required: true, description: '准备执行的视频/图片生成 prompt 或 storyboard。' },
      targetCapability: { type: 'string', description: '计划调用的 NexTide capability，例如 viral.midform.video.generate。' },
    },
    outputSchema: {
      verdict: { type: 'string', description: 'PASS / PASS_WITH_FIXES / RISKY_DO_NOT_RUN / UNDER_SPECIFIED。' },
      fixes: { type: 'array', description: '必须修复的问题。' },
    },
  },
  {
    id: 'content.visual_hook.design',
    skillName: 'visual-hook-optimizer',
    title: '视觉开头优化',
    description: '优化短视频第一帧、前 1-3 秒、小红书封面/首图，让画面产生明确 viewer question。',
    status: 'available',
    executionType: 'local_agent',
    async: false,
    maxWaitSeconds: 0,
    estimatedDurationSeconds: 60,
    featureKey: 'smart_creation',
    tags: ['visual-hook', 'first-frame', 'cover', 'short-video', 'local-agent'],
    inputSchema: {
      visualDescription: { type: 'string', required: true, description: '当前第一帧/首图/前 3 秒画面描述。' },
      goal: { type: 'string', description: '想让观众产生的问题或动作。' },
    },
    outputSchema: {
      visualHook: { type: 'object', description: 'Hook family、first frame、action、evidence、viewer question、next shot。' },
    },
  },
  {
    id: 'content.opening_pattern.route',
    skillName: 'opening-pattern-router',
    title: '短视频开头模式路由',
    description: '在写 hook/prompt/storyboard 前判断开头路线：自我识别、证明优先、好奇缺口、打断模式、社会后果或生活方式吸引。',
    status: 'available',
    executionType: 'local_agent',
    async: false,
    maxWaitSeconds: 0,
    estimatedDurationSeconds: 45,
    featureKey: 'smart_creation',
    tags: ['hook-router', 'opening-pattern', 'short-video', 'local-agent'],
    inputSchema: {
      brief: { type: 'string', required: true, description: '短视频任务、产品、观众或已有开头想法。' },
      segmentType: { type: 'string', description: 'hook / benefit / cta / creator / lifestyle / testimonial。' },
    },
    outputSchema: {
      routeSummary: { type: 'object', description: 'Segment type、primary pattern、viewer question、product reveal rule、next skill。' },
    },
  },
  {
    id: 'content.wechat.longform.write',
    skillName: 'wechat-longform-writer',
    title: '公众号长文写作',
    description: '使用公众号长文写作 skill 将素材写成公众号长文。',
    status: 'available',
    executionType: 'local_agent',
    async: false,
    maxWaitSeconds: 0,
    featureKey: 'script_generation',
    tags: ['wechat', 'longform', 'writing'],
    inputSchema: {
      material: { type: 'string', required: true, description: '写作素材。' },
    },
    outputSchema: {
      article: { type: 'string', description: '公众号文章。' },
    },
  },
];
