import type { AgentCapabilityDefinition } from '../types';

export const XHS_CAPABILITIES: AgentCapabilityDefinition[] = [
  {
    id: 'xhs.note.collect',
    skillName: 'xiaohongshu-note-collector',
    title: '小红书笔记采集',
    description: '采集小红书链接并沉淀为爆款广场/viral references 可用的结构化数据。MVP 阶段已支持 URL 采集，关键词搜索采集仍为 planned。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/miniapp/hot-square/collect-xhs',
    method: 'POST',
    async: true,
    maxWaitSeconds: 300,
    estimatedDurationSeconds: 60,
    featureKey: 'xhs_note_collect',
    tags: ['xiaohongshu', 'collection', 'hot-square', 'viral-reference'],
    inputSchema: {
      source: { type: 'string', required: true, enum: ['url', 'keyword'], description: '采集来源类型：url 或 keyword。' },
      urls: { type: 'string[]', description: '小红书笔记链接列表，source=url 时使用。' },
      keywords: { type: 'string[]', description: '搜索关键词，source=keyword 时使用。' },
      limit: { type: 'number', default: 30, description: '目标采集数量。' },
      collectComments: { type: 'boolean', default: false, description: '是否同时采集评论。默认关闭以节省成本。' },
      saveToHotSquare: { type: 'boolean', default: true, description: '是否保存到爆款广场/素材库。' },
    },
    outputSchema: {
      items: { type: 'array', description: '归一化后的小红书笔记列表。' },
      savedReferences: { type: 'array', description: '已保存的 viral reference 记录。' },
    },
  },
  {
    id: 'xhs.card.layout',
    skillName: 'xiaohongshu-card-layout',
    title: '小红书图文排版',
    description: '将 Markdown 文档排版并渲染为小红书 3:4 卡片图片。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/xhs-layout/render',
    method: 'POST',
    async: false,
    maxWaitSeconds: 120,
    estimatedDurationSeconds: 20,
    featureKey: 'xhs_card_layout',
    tags: ['xiaohongshu', 'layout', 'markdown', 'cards'],
    inputSchema: {
      markdown: { type: 'string', required: true, description: '要排版的 Markdown 正文。' },
      title: { type: 'string', description: '卡片标题。为空时自动从 Markdown 提取。' },
      templateId: { type: 'string', default: 'minimal', description: '卡片模板 ID。' },
      includeCover: { type: 'boolean', default: true, description: '是否生成封面页。' },
      maxPages: { type: 'number', default: 8, description: '最多生成页数。' },
      persist: { type: 'boolean', default: false, description: '是否保存为创作任务。' },
    },
    outputSchema: {
      taskId: { type: 'string', description: '保存任务 ID；persist=false 时为空。' },
      title: { type: 'string', description: '渲染标题。' },
      templateId: { type: 'string', description: '实际使用模板。' },
      images: { type: 'string[]', description: '生成的卡片图片 URL。' },
    },
  },
  {
    id: 'xhs.infographic.style.extract',
    skillName: 'xiaohongshu-infographic-generator',
    title: '小红书信息卡片风格提炼',
    description: '从参考图中提炼小红书信息卡片 Style DNA、版式规则和 prompt kit。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/assets/styles/upload',
    method: 'POST',
    async: true,
    maxWaitSeconds: 600,
    estimatedDurationSeconds: 180,
    featureKey: 'xhs_vision_style_web',
    workflowId: 'flow_xhs_Vision',
    workflowName: '小红书视觉风格分析',
    tags: ['xiaohongshu', 'style', 'infographic', 'style-dna'],
    inputSchema: {
      referenceImages: { type: 'string[]', required: true, description: '参考图片 URL 或已上传文件 URL。' },
      styleName: { type: 'string', description: '风格名称。' },
    },
    outputSchema: {
      stylePresetId: { type: 'string', description: '生成的风格预设 ID。' },
      styleDna: { type: 'object', description: '风格 DNA 结构化结果。' },
    },
  },
  {
    id: 'xhs.infographic.generate',
    skillName: 'xiaohongshu-infographic-generator',
    title: '小红书信息卡片生成',
    description: '根据主题、正文和风格预设生成小红书信息卡片。',
    status: 'available',
    executionType: 'internal_api',
    internalApiPath: '/api/xhs-text2img/plan',
    method: 'POST',
    async: true,
    maxWaitSeconds: 900,
    estimatedDurationSeconds: 240,
    featureKey: 'xhs_infographic_generate',
    tags: ['xiaohongshu', 'infographic', 'image-generation'],
    inputSchema: {
      topic: { type: 'string', required: true, description: '卡片主题。' },
      content: { type: 'string', required: true, description: '正文内容。' },
      stylePresetId: { type: 'string', description: '风格预设 ID。' },
      pageCount: { type: 'number', default: 6, description: '生成页数。' },
    },
    outputSchema: {
      jobId: { type: 'string', description: '生成任务 ID。' },
      cards: { type: 'array', description: '生成的卡片结果。' },
    },
  },
];
