type WidenStringLiterals<T> = T extends string
  ? string
  : T extends number | boolean | null
    ? T
    : T extends Array<infer U>
      ? Array<WidenStringLiterals<U>>
      : T extends Record<string, any>
        ? { [K in keyof T]: WidenStringLiterals<T[K]> }
        : T;

const assetLibraryTemplate = {
  sidebarLabel: "Knowledge Library",
  title: "AI Knowledge Library",
  subtitle:
    "Centralize viral scripts, channel stories, and branded visual presets so every workflow stays on brief.",
  tabs: {
    history: "History Docs",
    stories: "Story Assets",
    styles: "Style Presets",
  },
  common: {
    refresh: "Refresh Data",
    requiresAuth: "Please sign in to manage assets.",
    view: "View",
    uploadButton: "Upload",
    uploading: "Uploading...",
    status: "Status",
    size: "File Size",
    sourceFile: "Source File",
  },
  statusText: {
    pending: "Pending",
    processing: "Processing",
    ready: "Ready",
    completed: "Completed",
    failed: "Failed",
    importing: "Importing",
    queued: "Queued",
  },
  channelOptions: [
    { value: "douyin", label: "Douyin / TikTok" },
    { value: "kuaishou", label: "Kuaishou" },
    { value: "xiaohongshu", label: "Xiaohongshu" },
    { value: "weibo", label: "Weibo" },
    { value: "bilibili", label: "Bilibili" },
    { value: "youtube", label: "YouTube" },
    { value: "instagram", label: "Instagram" },
    { value: "facebook", label: "Facebook" },
    { value: "wechat", label: "WeChat Article" },
    { value: "offline", label: "Offline / OOH" },
  ],
  uploadHints: {
    file: "Supports .md / .docx / .pdf up to 10 MB.",
    image: "Supports JPG / PNG / WebP up to 5 MB.",
  },
  history: {
    uploadTitle: "Manual Upload",
    titlePlaceholder: "Untitled history doc",
    channelPlaceholder: "Channel or scenario",
    channelHelp: "Helps AI understand which platform the copy belongs to.",
    fileLabel: "Copy file",
    contentRequired: "Paste the copy before uploading.",
    manualInputLabel: "Paste winning copy",
    manualInputPlaceholder: "e.g. TikTok script, landing page teardown...",
    manualInputHint: "Markdown friendly. Keep headers with ### or bullet lists.",
    modeTabs: {
      manual: "Manual",
      bulk: "Bulk Import",
    },
    bulkTitle: "Bulk Import (Excel)",
    bulkDescription:
      "Download the template, paste multiple docs, then upload the completed sheet.",
    bulkTemplateLabel: "Download template",
    bulkFileLabel: "Upload completed template",
    bulkHint: "Accepted format: .xlsx up to 2 MB.",
    bulkProcessing: "Importing {count} docs...",
    bulkSuccess: "Imported {count} docs successfully.",
    previewTitle: "AI Preview",
    previewLoading: "Loading preview...",
    previewUnsupported: "Preview unavailable. Download the original file instead.",
    previewFailed: "Preview failed. Please download the original file.",
    empty: "No history docs yet. Upload your first winning copy.",
    deleteAction: "Delete Doc",
    deleteConfirm: "Delete this doc?",
    deleteSuccess: "Doc deleted.",
    detailTabs: {
      insights: "AI Insights",
      original: "Original File",
    },
    detailEmpty: "AI insights will appear after processing.",
    detailLoading: "Generating insights...",
    detailRetry: "Refresh",
    originalUnavailable: "Original file unavailable.",
    insightsEmpty: "Insights are not ready yet.",
  },
  stories: {
    uploadTitle: "Story Upload",
    titlePlaceholder: "Story title",
    summaryPlaceholder: "One-line summary or hook",
    channelPlaceholder: "Channel",
    fileLabel: "Reference file",
    contentRequired: "Please add the story body or upload a file.",
    bodyLabel: "Story body",
    bodyPlaceholder: "Break down angles, hook, CTA, structure...",
    bodyHint: "Markdown supported.",
    modeTabs: {
      manual: "Manual",
      bulk: "Bulk Import",
    },
    bulkTitle: "Bulk Import (Excel)",
    bulkDescription: "Use the template to add multiple stories at once.",
    bulkTemplateLabel: "Download template",
    bulkFileLabel: "Upload completed template",
    bulkHint: "Accepted format: .xlsx up to 2 MB.",
    bulkProcessing: "Importing {count} stories...",
    bulkSuccess: "Imported {count} stories successfully.",
    bulkFailure: "Import failed. Please check the template.",
    deleteAction: "Delete Story",
    deleteConfirm: "Delete this story asset?",
    deleteSuccess: "Story deleted.",
    empty: "No story assets yet.",
  },
  styles: {
    uploadTitle: "Upload Style Preset",
    namePlaceholder: "Preset name (e.g. Retro Grid Visual)",
    autoAnalyzeNote: "Meta data like palette and tone will be auto-extracted.",
    typeHint: "Choose the rendering target used in workflows.",
    typeOptions: {
      "xhs-visual": "Xiaohongshu Visual",
      "douyin-visual": "Douyin Visual",
      poster: "Poster Layout",
      video: "Video Overlay",
    },
    fileLabel: "Preset file / reference image",
    empty: "No custom styles yet.",
  },
  analysisSummaryLabel: "AI Summary",
  voiceProfileLabel: "Voice Profile",
  voicePersonaLabel: "Persona",
  voiceCadenceLabel: "Cadence",
  mustIncludeLabel: "Must Include",
  avoidLabel: "Avoid",
  structureLabel: "Structure Breakdown",
  structureSummaryFallback: "No summary yet.",
  structureKeywordsLabel: "Keywords",
  sectionLabelFallback: "Section {index}",
  reusableLabel: "Reusable Blocks",
  hooksLabel: "Hooks",
  transitionsLabel: "Transitions",
  closersLabel: "Closers",
  proofPointsLabel: "Proof Points",
} as const;

export type AssetLibraryCopy = WidenStringLiterals<typeof assetLibraryTemplate>;

export const assetLibraryEn: AssetLibraryCopy = assetLibraryTemplate;

export const assetLibraryZh = {
  sidebarLabel: "知识库",
  title: "AI 知识库",
  subtitle: "集中管理爆款脚本、案例拆解和视觉风格，让后续流程始终对齐调性。",
  tabs: {
    history: "历史文案",
    stories: "案例故事",
    styles: "风格预设",
  },
  common: {
    refresh: "刷新数据",
    requiresAuth: "请先登录以管理资产。",
    view: "查看",
    uploadButton: "上传",
    uploading: "正在上传...",
    status: "状态",
    size: "文件大小",
    sourceFile: "源文件",
  },
  statusText: {
    pending: "排队中",
    processing: "处理中",
    ready: "已就绪",
    completed: "已完成",
    failed: "失败",
    importing: "导入中",
    queued: "排队中",
  },
  channelOptions: [
    { value: "douyin", label: "抖音 / TikTok" },
    { value: "kuaishou", label: "快手" },
    { value: "xiaohongshu", label: "小红书" },
    { value: "weibo", label: "微博" },
    { value: "bilibili", label: "B站" },
    { value: "youtube", label: "YouTube" },
    { value: "instagram", label: "Instagram" },
    { value: "facebook", label: "Facebook" },
    { value: "wechat", label: "微信公众号" },
    { value: "offline", label: "线下 / OOH" },
  ],
  uploadHints: {
    file: "支持 .md / .docx / .pdf，最大 10MB。",
    image: "支持 JPG / PNG / WebP，最大 5MB。",
  },
  history: {
    uploadTitle: "手动上传",
    titlePlaceholder: "未命名历史文案",
    channelPlaceholder: "投放渠道 / 使用场景",
    channelHelp: "帮助模型理解文案所在的平台。",
    fileLabel: "文案文件",
    contentRequired: "请先粘贴文案内容。",
    manualInputLabel: "粘贴爆款文案",
    manualInputPlaceholder: "例如：爆款短视频脚本、长图文拆解...",
    manualInputHint: "支持 Markdown，使用 ### 保留小标题。",
    modeTabs: {
      manual: "手动",
      bulk: "批量导入",
    },
    bulkTitle: "批量导入（Excel）",
    bulkDescription: "下载模板，粘贴多篇文案后上传填写好的表格。",
    bulkTemplateLabel: "下载 Excel 模板",
    bulkFileLabel: "上传模板文件",
    bulkHint: "仅支持 .xlsx，最大 2MB。",
    bulkProcessing: "正在导入 {count} 篇文档...",
    bulkSuccess: "{count} 篇文档导入完成。",
    previewTitle: "AI 预览",
    previewLoading: "正在加载预览...",
    previewUnsupported: "暂不支持预览，请下载原文件。",
    previewFailed: "预览失败，请下载原文件。",
    empty: "还没有历史文案，马上上传第一篇吧。",
    deleteAction: "删除文档",
    deleteConfirm: "确定要删除该文档？",
    deleteSuccess: "文档已删除。",
    detailTabs: {
      insights: "AI 拆解",
      original: "原文件",
    },
    detailEmpty: "暂无 AI 拆解内容。",
    detailLoading: "AI 正在生成拆解...",
    detailRetry: "刷新",
    originalUnavailable: "原文件不可用。",
    insightsEmpty: "处理完成后会展示拆解结果。",
  },
  stories: {
    uploadTitle: "案例故事上传",
    titlePlaceholder: "案例标题",
    summaryPlaceholder: "一句话亮点",
    channelPlaceholder: "渠道",
    fileLabel: "参考文件",
    contentRequired: "请填写故事正文或上传文件。",
    bodyLabel: "故事正文",
    bodyPlaceholder: "拆解结构、开头、CTA 等...",
    bodyHint: "支持 Markdown。",
    modeTabs: {
      manual: "手动",
      bulk: "批量导入",
    },
    bulkTitle: "批量导入（Excel）",
    bulkDescription: "使用模板一次导入多个案例故事。",
    bulkTemplateLabel: "下载 Excel 模板",
    bulkFileLabel: "上传模板文件",
    bulkHint: "仅支持 .xlsx，最大 2MB。",
    bulkProcessing: "正在导入 {count} 个故事...",
    bulkSuccess: "{count} 个故事导入完成。",
    bulkFailure: "导入失败，请检查模板。",
    deleteAction: "删除故事",
    deleteConfirm: "确定要删除该案例？",
    deleteSuccess: "故事已删除。",
    empty: "暂无案例故事。",
  },
  styles: {
    uploadTitle: "上传风格预设",
    namePlaceholder: "预设名称（例如：复古九宫格）",
    autoAnalyzeNote: "系统会自动抽取配色、调性等信息。",
    typeHint: "选择适用场景，方便任务自动匹配。",
    typeOptions: {
      "xhs-visual": "小红书视觉",
      "douyin-visual": "抖音视觉",
      poster: "海报布局",
      video: "视频贴图/字幕",
    },
    fileLabel: "预设文件 / 参考图片",
    empty: "暂无自定义风格。",
  },
  analysisSummaryLabel: "AI 摘要",
  voiceProfileLabel: "声音画像",
  voicePersonaLabel: "人设",
  voiceCadenceLabel: "节奏 / 语气",
  mustIncludeLabel: "必须包含",
  avoidLabel: "避免",
  structureLabel: "结构拆解",
  structureSummaryFallback: "暂无摘要。",
  structureKeywordsLabel: "关键词",
  sectionLabelFallback: "第 {index} 段",
  reusableLabel: "可复用模块",
  hooksLabel: "开场 Hook",
  transitionsLabel: "转场",
  closersLabel: "收尾",
  proofPointsLabel: "信任背书",
} as const satisfies AssetLibraryCopy;

export const assetLibraryZhTw = {
  sidebarLabel: "知識庫",
  title: "AI 知識庫",
  subtitle: "集中管理爆款腳本、案例拆解與視覺風格，讓流程始終保持一致。",
  tabs: {
    history: "歷史文案",
    stories: "案例故事",
    styles: "風格預設",
  },
  common: {
    refresh: "刷新資料",
    requiresAuth: "請先登入以管理資產。",
    view: "查看",
    uploadButton: "上傳",
    uploading: "正在上傳...",
    status: "狀態",
    size: "檔案大小",
    sourceFile: "來源檔案",
  },
  statusText: {
    pending: "排隊中",
    processing: "處理中",
    ready: "已就緒",
    completed: "已完成",
    failed: "失敗",
    importing: "匯入中",
    queued: "排隊中",
  },
  channelOptions: [
    { value: "douyin", label: "抖音 / TikTok" },
    { value: "kuaishou", label: "快手" },
    { value: "xiaohongshu", label: "小紅書" },
    { value: "weibo", label: "微博" },
    { value: "bilibili", label: "B站" },
    { value: "youtube", label: "YouTube" },
    { value: "instagram", label: "Instagram" },
    { value: "facebook", label: "Facebook" },
    { value: "wechat", label: "微信公眾號" },
    { value: "offline", label: "線下 / OOH" },
  ],
  uploadHints: {
    file: "支援 .md / .docx / .pdf，最大 10MB。",
    image: "支援 JPG / PNG / WebP，最大 5MB。",
  },
  history: {
    uploadTitle: "手動上傳",
    titlePlaceholder: "未命名歷史文案",
    channelPlaceholder: "投放渠道 / 使用情境",
    channelHelp: "協助模型理解文案來源的平台。",
    fileLabel: "文案檔案",
    contentRequired: "請先貼上文案內容。",
    manualInputLabel: "貼上爆款文案",
    manualInputPlaceholder: "例如：爆款短影片腳本、長文拆解...",
    manualInputHint: "支援 Markdown，使用 ### 保留小標題。",
    modeTabs: {
      manual: "手動",
      bulk: "批次匯入",
    },
    bulkTitle: "批次匯入（Excel）",
    bulkDescription: "下載模板，貼上多篇文案後再上傳完整表格。",
    bulkTemplateLabel: "下載 Excel 模板",
    bulkFileLabel: "上傳模板檔案",
    bulkHint: "僅支援 .xlsx，最大 2MB。",
    bulkProcessing: "正在匯入 {count} 篇文件...",
    bulkSuccess: "{count} 篇文件匯入完成。",
    previewTitle: "AI 預覽",
    previewLoading: "正在載入預覽...",
    previewUnsupported: "暫不支援預覽，請下載原檔。",
    previewFailed: "預覽失敗，請下載原檔。",
    empty: "尚未新增歷史文案。",
    deleteAction: "刪除文件",
    deleteConfirm: "確定要刪除該文件？",
    deleteSuccess: "文件已刪除。",
    detailTabs: {
      insights: "AI 拆解",
      original: "原始檔",
    },
    detailEmpty: "暫無 AI 拆解內容。",
    detailLoading: "AI 正在產生拆解...",
    detailRetry: "重新整理",
    originalUnavailable: "原始檔不可用。",
    insightsEmpty: "處理完成後將顯示拆解結果。",
  },
  stories: {
    uploadTitle: "案例故事上傳",
    titlePlaceholder: "案例標題",
    summaryPlaceholder: "一句話亮點",
    channelPlaceholder: "渠道",
    fileLabel: "參考檔案",
    contentRequired: "請填寫故事本文或上傳檔案。",
    bodyLabel: "故事本文",
    bodyPlaceholder: "拆解結構、開頭、CTA 等...",
    bodyHint: "支援 Markdown。",
    modeTabs: {
      manual: "手動",
      bulk: "批次匯入",
    },
    bulkTitle: "批次匯入（Excel）",
    bulkDescription: "使用模板一次匯入多個案例故事。",
    bulkTemplateLabel: "下載 Excel 模板",
    bulkFileLabel: "上傳模板檔案",
    bulkHint: "僅支援 .xlsx，最大 2MB。",
    bulkProcessing: "正在匯入 {count} 個故事...",
    bulkSuccess: "{count} 個故事匯入完成。",
    bulkFailure: "匯入失敗，請檢查模板。",
    deleteAction: "刪除故事",
    deleteConfirm: "確定要刪除此案例？",
    deleteSuccess: "故事已刪除。",
    empty: "暫無案例故事。",
  },
  styles: {
    uploadTitle: "上傳風格預設",
    namePlaceholder: "預設名稱（例如：復古九宮格）",
    autoAnalyzeNote: "系統會自動擷取配色、調性等資訊。",
    typeHint: "選擇使用場景以便任務自動套用。",
    typeOptions: {
      "xhs-visual": "小紅書視覺",
      "douyin-visual": "抖音視覺",
      poster: "海報版面",
      video: "影片貼圖 / 字幕",
    },
    fileLabel: "預設檔案 / 參考圖片",
    empty: "尚無自訂風格。",
  },
  analysisSummaryLabel: "AI 摘要",
  voiceProfileLabel: "聲音輪廓",
  voicePersonaLabel: "人設",
  voiceCadenceLabel: "節奏 / 語氣",
  mustIncludeLabel: "必須包含",
  avoidLabel: "避免",
  structureLabel: "結構拆解",
  structureSummaryFallback: "暫無摘要。",
  structureKeywordsLabel: "關鍵詞",
  sectionLabelFallback: "第 {index} 段",
  reusableLabel: "可複用模組",
  hooksLabel: "開場 Hook",
  transitionsLabel: "轉場",
  closersLabel: "結尾",
  proofPointsLabel: "信任背書",
} as const satisfies AssetLibraryCopy;
