import prisma from "@/lib/prisma";

const DEFAULT_CREDIT_CONFIGS = [
  // Canvas 图片
  {
    featureKey: "canvas_image_generation",
    featureName: "Canvas 图片生成",
    category: "canvas_image",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "Canvas 图片生成（功能级兜底价）",
  },
  {
    featureKey: "canvas_grid_split",
    featureName: "Canvas 九宫格拆图",
    category: "canvas_image",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "Canvas 九宫格图片拆分（固定费用）",
  },
  {
    featureKey: "canvas_image_generation:nano-banana",
    featureName: "Canvas 图片 · Nano Banana",
    category: "canvas_image",
    modelKey: "nano-banana",
    amount: 1,
    enabled: true,
    description: "Canvas 图片生成（nano-banana / Gemini Flash）",
  },
  {
    featureKey: "canvas_image_generation:nano-banana-pro",
    featureName: "Canvas 图片 · Nano Banana Pro",
    category: "canvas_image",
    modelKey: "nano-banana-pro",
    amount: 2,
    enabled: true,
    description: "Canvas 图片生成（nano-banana-pro / Gemini Pro）",
  },
  // Canvas 视频
  {
    featureKey: "canvas_video_generation",
    featureName: "Canvas 视频生成",
    category: "canvas_video",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "Canvas 视频生成（功能级兜底价）",
  },
  {
    featureKey: "canvas_video_generation:veo3",
    featureName: "Canvas 视频 · Veo3",
    category: "canvas_video",
    modelKey: "veo3",
    amount: 5,
    enabled: true,
    description: "Canvas 视频生成（Veo3 标准版）",
  },
  {
    featureKey: "canvas_video_generation:veo3-fast",
    featureName: "Canvas 视频 · Veo3 Fast",
    category: "canvas_video",
    modelKey: "veo3-fast",
    amount: 3,
    enabled: true,
    description: "Canvas 视频生成（Veo3 快速版）",
  },
  {
    featureKey: "canvas_video_generation:sora2",
    featureName: "Canvas 视频 · Sora2",
    category: "canvas_video",
    modelKey: "sora2",
    amount: 5,
    enabled: true,
    description: "Canvas 视频生成（Sora2）",
  },
  {
    featureKey: "canvas_video_generation:grok3",
    featureName: "Canvas 视频 · Grok3",
    category: "canvas_video",
    modelKey: "grok3",
    amount: 4,
    enabled: true,
    description: "Canvas 视频生成（Grok3）",
  },
  {
    featureKey: "miniapp_canvas_image",
    featureName: "小程序 AI 作图",
    category: "canvas_image",
    modelKey: null,
    amount: 40,
    enabled: true,
    description: "小程序 AI 作图（功能级兜底价，按张计费）",
  },
  {
    featureKey: "miniapp_canvas_image:image2",
    featureName: "小程序 AI 作图 · GPT-image2",
    category: "canvas_image",
    modelKey: "image2",
    amount: 40,
    enabled: true,
    description: "小程序 AI 作图 image2 工作流，按张计费",
  },
  {
    featureKey: "miniapp_canvas_image:nano-banana-pro",
    featureName: "小程序 AI 作图 · Nano Banana Pro",
    category: "canvas_image",
    modelKey: "nano-banana-pro",
    amount: 40,
    enabled: true,
    description: "小程序 AI 作图 Nano Banana Pro，按张计费",
  },
  {
    featureKey: "canvas_grid_generation",
    featureName: "Canvas 九宫格生成",
    category: "canvas_image",
    modelKey: null,
    amount: 50,
    enabled: true,
    description: "Canvas 九宫格分镜图生成",
  },
  {
    featureKey: "canvas_audio_generation",
    featureName: "Canvas 音频生成",
    category: "content_generation",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "Canvas 音频/配音生成（功能级兜底价）",
  },
  {
    featureKey: "canvas_text_transform",
    featureName: "Canvas 文本改写",
    category: "content_generation",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "Canvas LLM 文本处理（可按模型加 :modelKey）",
  },
  {
    featureKey: "canvas_image_understanding",
    featureName: "Canvas 图片理解",
    category: "content_generation",
    modelKey: null,
    amount: 15,
    enabled: true,
    description: "Canvas 图片理解 / 多模态分析（可按模型加 :modelKey）",
  },
  // 分镜
  {
    featureKey: "storyboard_breakdown",
    featureName: "分镜拆解",
    category: "storyboard",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "爆款复刻视频拆解分镜（固定费用）",
  },
  {
    featureKey: "storyboard_skeleton_breakdown",
    featureName: "3D骨骼分镜拆解",
    category: "storyboard",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "3D骨骼分镜视频拆解（固定费用）",
  },
  {
    featureKey: "storyboard_image",
    featureName: "分镜首帧图生成",
    category: "storyboard",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "分镜板首帧图生成，按分镜数计费",
  },
  {
    featureKey: "storyboard_image:image2",
    featureName: "分镜首帧图生成 · GPT-image2",
    category: "storyboard",
    modelKey: "image2",
    amount: 1,
    enabled: true,
    description: "分镜板首帧图生成（image2）",
  },
  {
    featureKey: "storyboard_image:nano-banana-pro",
    featureName: "分镜首帧图生成 · Nano Banana Pro",
    category: "storyboard",
    modelKey: "nano-banana-pro",
    amount: 2,
    enabled: true,
    description: "分镜板首帧图生成（Nano Banana Pro）",
  },
  {
    featureKey: "storyboard_video",
    featureName: "分镜视频生成",
    category: "storyboard",
    modelKey: null,
    amount: 3,
    enabled: true,
    description: "分镜板视频生成（通用兜底价，按分镜数计费）",
  },
  {
    featureKey: "storyboard_split",
    featureName: "分镜拆分",
    category: "storyboard",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "视频分镜拆解（固定费用）",
  },
  {
    featureKey: "storyboard_job_create",
    featureName: "分镜任务创建",
    category: "storyboard",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "创建分镜任务并触发上游分镜编排",
  },
  {
    featureKey: "storyboard_video:veo3",
    featureName: "分镜视频生成 · Veo3",
    category: "storyboard",
    modelKey: "veo3",
    amount: 5,
    enabled: true,
    description: "分镜视频生成（Veo3 标准版）",
  },
  {
    featureKey: "storyboard_video:veo3-fast",
    featureName: "分镜视频生成 · Veo3 Fast",
    category: "storyboard",
    modelKey: "veo3-fast",
    amount: 3,
    enabled: true,
    description: "分镜视频生成（Veo3 快速版）",
  },
  {
    featureKey: "storyboard_video:veo3.1-fast",
    featureName: "分镜视频生成 · Veo3.1 Fast",
    category: "storyboard",
    modelKey: "veo3.1-fast",
    amount: 3,
    enabled: true,
    description: "分镜视频生成（Veo3.1 快速版）",
  },
  {
    featureKey: "storyboard_video:bytedance/seedance-2",
    featureName: "分镜视频生成 · Seedance 2.0",
    category: "storyboard",
    modelKey: "bytedance/seedance-2",
    amount: 4,
    enabled: true,
    description: "分镜视频生成（Seedance 2.0 标准版，按秒计费）",
  },
  {
    featureKey: "storyboard_video:bytedance/seedance-2-fast",
    featureName: "分镜视频生成 · Seedance 2.0 Fast",
    category: "storyboard",
    modelKey: "bytedance/seedance-2-fast",
    amount: 3,
    enabled: true,
    description: "分镜视频生成（Seedance 2.0 快速版，按秒计费）",
  },
  {
    featureKey: "storyboard_video:bytedance/seedance-2.0",
    featureName: "分镜视频生成 · Seedance 2.0",
    category: "storyboard",
    modelKey: "bytedance/seedance-2.0",
    amount: 4,
    enabled: true,
    description: "分镜视频生成（Seedance 2.0 标准版，兼容 2.0 写法，按秒计费）",
  },
  {
    featureKey: "storyboard_video:bytedance/seedance-2.0-fast",
    featureName: "分镜视频生成 · Seedance 2.0 Fast",
    category: "storyboard",
    modelKey: "bytedance/seedance-2.0-fast",
    amount: 3,
    enabled: true,
    description: "分镜视频生成（Seedance 2.0 快速版，兼容 2.0 写法，按秒计费）",
  },
  // 其他固定费用功能
  {
    featureKey: "image_text_replication",
    featureName: "图文复刻",
    category: "replication",
    modelKey: null,
    amount: 2,
    enabled: true,
    description: "图文内容复刻（固定费用）",
  },
  {
    featureKey: "image_text_replication:start",
    featureName: "图文复刻 · 拆解建任务",
    category: "replication",
    modelKey: "start",
    amount: 1,
    enabled: true,
    description: "图文复刻起点任务创建与后台拆解",
  },
  {
    featureKey: "image_text_replication:breakdown",
    featureName: "图文复刻 · 图片拆解",
    category: "replication",
    modelKey: "breakdown",
    amount: 5,
    enabled: true,
    description: "图文复刻图片文案识别 / OCR 拆解",
  },
  {
    featureKey: "image_text_replication:generate",
    featureName: "图文复刻 · 图片生成",
    category: "replication",
    modelKey: "generate",
    amount: 2,
    enabled: true,
    description: "图文复刻标题正文改写后触发生成",
  },
  {
    featureKey: "image_text_replication:extract-video-copy",
    featureName: "图文复刻 · 视频文案提取",
    category: "replication",
    modelKey: "extract-video-copy",
    amount: 2,
    enabled: true,
    description: "图文复刻视频口播文案提取",
  },
  {
    featureKey: "writing_style_extraction",
    featureName: "写作风格提取",
    category: "writing_style",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "写作风格提取分析（固定费用）",
  },
  {
    featureKey: "xhs_note_collect",
    featureName: "小红书笔记采集",
    category: "xhs",
    modelKey: null,
    amount: 5,
    enabled: true,
    description: "小红书笔记 URL 采集并保存到素材库",
  },
  {
    featureKey: "xhs_card_layout",
    featureName: "小红书图文排版",
    category: "smart_creation",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "小红书 Markdown 图文排版",
  },
  {
    featureKey: "xhs_layout_normalize",
    featureName: "小红书 AI 排版",
    category: "smart_creation",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "小红书 Markdown 预览区 AI 排版（仅调整排版，不改写内容）",
  },
  {
    featureKey: "xhs_infographic_generate",
    featureName: "小红书信息卡片生成",
    category: "smart_creation",
    modelKey: null,
    amount: 10,
    enabled: true,
    description: "小红书信息卡片生成",
  },
  {
    featureKey: "xhs_vision_style_web",
    featureName: "小红书视觉风格分析",
    category: "smart_creation",
    modelKey: null,
    amount: 8,
    enabled: true,
    description: "小红书视觉风格提炼 / Style DNA",
  },
  {
    featureKey: "my_note_breakdown",
    featureName: "我的笔记 · 图片解析",
    category: "replication",
    modelKey: "gemini-3.1-flash-lite-preview",
    amount: 5,
    enabled: true,
    description: "我的笔记图片 OCR 解析，按图计费",
  },
  {
    featureKey: "my_note_breakdown_retry",
    featureName: "我的笔记 · 图片解析重试",
    category: "replication",
    modelKey: "gemini-3.1-flash-lite-preview",
    amount: 1,
    enabled: true,
    description: "我的笔记单张图片重试识别",
  },
  {
    featureKey: "my_note_rewrite",
    featureName: "我的笔记 · 一键仿写",
    category: "replication",
    modelKey: "xhs_rewrite",
    amount: 1,
    enabled: true,
    description: "我的笔记标题/正文/图片文案二创",
  },
  {
    featureKey: "digital_human",
    featureName: "数字人视频",
    category: "digital_human",
    modelKey: null,
    amount: 3,
    enabled: true,
    description: "数字人口播视频生成（固定费用）",
  },
  {
    featureKey: "digital_human:flow_digital_human",
    featureName: "数字人视频 · 标准",
    category: "digital_human",
    modelKey: "flow_digital_human",
    amount: 30,
    enabled: true,
    description: "数字人口播视频生成标准工作流",
  },
  {
    featureKey: "digital_human:flow_digital_human16s",
    featureName: "数字人视频 · 16s",
    category: "digital_human",
    modelKey: "flow_digital_human16s",
    amount: 15,
    enabled: true,
    description: "数字人口播短视频工作流",
  },
  {
    featureKey: "action_transfer",
    featureName: "动作复刻",
    category: "digital_human",
    modelKey: null,
    amount: 30,
    enabled: true,
    description: "动作迁移 / 图片驱动视频（功能级兜底价）",
  },
  {
    featureKey: "action_transfer:flow_action_transfer_wan_animate",
    featureName: "动作复刻 · Wan Animate",
    category: "digital_human",
    modelKey: "flow_action_transfer_wan_animate",
    amount: 30,
    enabled: true,
    description: "动作迁移 Wan Animate 工作流",
  },
  {
    featureKey: "knowledge_video",
    featureName: "知识视频",
    category: "knowledge_video",
    modelKey: null,
    amount: 2,
    enabled: true,
    description: "知识讲解视频生成（固定费用）",
  },
  {
    featureKey: "monetization_ai_tool_leads_video",
    featureName: "变现广场 · AI工具引流视频",
    category: "smart_creation",
    modelKey: null,
    amount: 3,
    enabled: true,
    description: "变现广场 AI 工具引流视频入口",
  },
  {
    featureKey: "social_tiktok_collect",
    featureName: "TikTok 数据采集",
    category: "social",
    modelKey: null,
    amount: 5,
    enabled: true,
    description: "TikTok 数据采集",
  },
  {
    featureKey: "monetization_ai_knowledge_card",
    featureName: "变现广场 · AI知识卡片",
    category: "smart_creation",
    modelKey: null,
    amount: 10,
    enabled: true,
    description: "变现广场 AI 知识卡片入口",
  },
  {
    featureKey: "monetization_startup_longform",
    featureName: "变现广场 · 创业知识长文",
    category: "smart_creation",
    modelKey: null,
    amount: 5,
    enabled: true,
    description: "变现广场创业知识长文入口",
  },
  {
    featureKey: "monetization_wellness_graphic",
    featureName: "变现广场 · 养生图文",
    category: "smart_creation",
    modelKey: null,
    amount: 10,
    enabled: true,
    description: "变现广场养生图文入口",
  },
  {
    featureKey: "monetization_finance_card",
    featureName: "变现广场 · 理财知识卡片",
    category: "smart_creation",
    modelKey: null,
    amount: 10,
    enabled: true,
    description: "变现广场理财知识卡片入口",
  },
  {
    featureKey: "monetization_ai_tool_leads_graphic",
    featureName: "变现广场 · AI工具引流图文",
    category: "smart_creation",
    modelKey: null,
    amount: 10,
    enabled: true,
    description: "变现广场 AI 工具引流图文入口",
  },
  {
    featureKey: "social_instagram_collect",
    featureName: "Instagram 数据采集",
    category: "social",
    modelKey: null,
    amount: 5,
    enabled: true,
    description: "Instagram 账号、帖子或 Reels 数据采集",
  },
  {
    featureKey: "social_facebook_collect",
    featureName: "Facebook 数据采集",
    category: "social",
    modelKey: null,
    amount: 5,
    enabled: true,
    description: "Facebook 公开页面、帖子或相关爆款内容采集",
  },
  {
    featureKey: "social_comments_collect",
    featureName: "社媒评论抓取",
    category: "social",
    modelKey: null,
    amount: 5,
    enabled: true,
    description: "TikTok 等平台评论抓取",
  },
  // 智能创作
  {
    featureKey: "smart_creation",
    featureName: "智能创作（一键成片）",
    category: "smart_creation",
    modelKey: null,
    amount: 3,
    enabled: true,
    description: "首页智能创作 / 爆款复刻一键成片（固定费用）",
  },
  {
    featureKey: "creative_generation",
    featureName: "智能创作文案生成",
    category: "smart_creation",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "智能创作任务文案生成",
  },
  {
    featureKey: "creative_stage_generation",
    featureName: "智能创作阶段生成",
    category: "smart_creation",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "智能创作单阶段生成，可按 stage 加 :stage",
  },
  {
    featureKey: "xhs_vision_style_web",
    featureName: "小红书视觉风格分析",
    category: "smart_creation",
    modelKey: null,
    amount: 8,
    enabled: true,
    description: "小红书视觉风格提炼 / Style DNA",
  },
  // 产品与脚本分析
  {
    featureKey: "product_analysis",
    featureName: "产品分析",
    category: "content_generation",
    modelKey: null,
    amount: 2,
    enabled: true,
    description: "上传产品后 AI 分析卖点与描述（固定费用）",
  },
  {
    featureKey: "selling_points_generation",
    featureName: "卖点生成脚本",
    category: "content_generation",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "基于卖点生成营销脚本（固定费用）",
  },
  {
    featureKey: "script_generation",
    featureName: "脚本生成",
    category: "content_generation",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "基于脚本内容生成创作内容（固定费用）",
  },
  {
    featureKey: "script_analysis",
    featureName: "脚本分析",
    category: "content_generation",
    modelKey: null,
    amount: 2,
    enabled: true,
    description: "上传脚本后 AI 拆解分析（固定费用）",
  },
  // 时间轴 / 分镜拼接
  {
    featureKey: "storyboard_merge",
    featureName: "成片剪辑",
    category: "storyboard",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "时间轴分镜视频合并剪辑（固定费用）",
  },
  {
    featureKey: "storyboard_subtitle",
    featureName: "分镜字幕生成",
    category: "storyboard",
    modelKey: null,
    amount: 1,
    enabled: true,
    description: "分镜视频自动生成字幕（固定费用）",
  },
  // AI 对话助手（按模型计费）
  {
    featureKey: "ai_agent:default",
    featureName: "AI 助手 · 默认模型",
    category: "ai_agent",
    modelKey: "default",
    amount: 1,
    enabled: true,
    description: "AI 对话助手每次会话扣除积分（默认模型）",
  },
  {
    featureKey: "ai_agent:gpt-4o",
    featureName: "AI 助手 · GPT-4o",
    category: "ai_agent",
    modelKey: "gpt-4o",
    amount: 3,
    enabled: true,
    description: "AI 对话助手每次会话扣除积分（GPT-4o）",
  },
  {
    featureKey: "ai_agent:claude-opus",
    featureName: "AI 助手 · Claude Opus",
    category: "ai_agent",
    modelKey: "claude-opus",
    amount: 5,
    enabled: true,
    description: "AI 对话助手每次会话扣除积分（Claude Opus）",
  },
  {
    featureKey: "ai_agent:deepseek-r1",
    featureName: "AI 助手 · DeepSeek R1",
    category: "ai_agent",
    modelKey: "deepseek-r1",
    amount: 2,
    enabled: true,
    description: "AI 对话助手每次会话扣除积分（DeepSeek R1）",
  },
];

async function main() {
  console.log("Seeding credit configs...");
  let created = 0;
  let skipped = 0;

  for (const config of DEFAULT_CREDIT_CONFIGS) {
    const result = await prisma.creditConfig.upsert({
      where: { featureKey: config.featureKey },
      create: config,
      update: {}, // 不覆盖 admin 已修改的值
    });
    if (result.createdAt.getTime() === result.updatedAt.getTime()) {
      created++;
    } else {
      skipped++;
    }
  }

  console.log(`Done: ${created} created, ${skipped} skipped (already exist).`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  prisma.$disconnect();
  process.exit(1);
});
