export default defineAppConfig({
  lazyCodeLoading: 'requiredComponents',
  pages: [
    'pages/home/index',
    'pages/hot-square/index',
    'pages/favorites/index',
    'pages/hot-detail/index',
    'pages/asset-center/index',
    'pages/works/index',
    'pages/work-detail/index',
    'pages/storyboard-board/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/login-phone/index',
    'pages/login-email/index',
    'pages/login-password/index',
    'pages/warehouse/index',
    'pages/product-library/index',
    'pages/style-library/index',
    'pages/remix-generate/index',
    'pages/generate/index',
    'pages/monetization-square/index',
    'pages/image-generate/index',
    'pages/records/index',
    'pages/points-records/index',
    'pages/referrals/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#050505',
    navigationBarTitleText: '小蚁AI',
    navigationBarTextStyle: 'white',
    backgroundColor: '#050505',
    navigationStyle: 'custom',
  },
  tabBar: {
    color: '#8f8a81',
    selectedColor: '#ecee9f',
    backgroundColor: '#050505',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/icons/home.png',
        selectedIconPath: 'assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/hot-square/index',
        text: '爆款',
        iconPath: 'assets/icons/hot-flame.png',
        selectedIconPath: 'assets/icons/hot-flame-active.png',
      },
      {
        pagePath: 'pages/works/index',
        text: '作品',
        iconPath: 'assets/icons/records.png',
        selectedIconPath: 'assets/icons/records-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/icons/profile.png',
        selectedIconPath: 'assets/icons/profile-active.png',
      },
    ],
  },
});
