export default defineAppConfig({
  // 微信小程序代码质量项：启用组件按需注入
  lazyCodeLoading: 'requiredComponents',
  pages: [
    'pages/home/index',
    'pages/hot-square/index',
    'pages/works/index',
    'pages/profile/index',
  ],
  subPackages: [
    {
      root: 'subpages',
      pages: [
        'favorites/index',
        'hot-detail/index',
        'asset-center/index',
        'work-detail/index',
        'storyboard-board/index',
        'login/index',
        'login-phone/index',
        'login-email/index',
        'login-password/index',
        'warehouse/index',
        'product-library/index',
        'style-library/index',
        'remix-generate/index',
        'generate/index',
        'monetization-square/index',
        'image-generate/index',
        'records/index',
        'points-records/index',
        'referrals/index',
      ],
    },
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#050505',
    navigationBarTitleText: '小蚁AI',
    navigationBarTextStyle: 'white',
    backgroundColor: '#050505',
    navigationStyle: 'custom',
  },
  tabBar: {
    color: '#8f8a81',
    selectedColor: '#ecee9f',
    backgroundColor: '#050505',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/icons/home.png',
        selectedIconPath: 'assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/hot-square/index',
        text: '爆款',
        iconPath: 'assets/icons/hot-flame.png',
        selectedIconPath: 'assets/icons/hot-flame-active.png',
      },
      {
        pagePath: 'pages/works/index',
        text: '作品',
        iconPath: 'assets/icons/records.png',
        selectedIconPath: 'assets/icons/records-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/icons/profile.png',
        selectedIconPath: 'assets/icons/profile-active.png',
      },
    ],
  },
});
